    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.qualita.controllo.MisuraCaracteriche', 'it.mame.thip.qualita.controllo.YMisuraCaracteriche', '0', 'Y');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.qualita.controllo.MisuraCaractericheTM', 'it.mame.thip.qualita.controllo.YMisuraCaractericheTM', '0', 'Y');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('MisuraCaratteristica', 'YMisuraCaracteriche', '1', 'Y');
