# Class path : com.thera.thermfw.util.Replacement
# Class name : REPLACEMENT
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.qualita.controllo.web.CicloCollaudoFaseFormModifier', 'it.mame.thip.qualita.controllo.web.YCicloCollaudoFaseFormModifier', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.qualita.controllo.CicloCollaudoFase', 'it.mame.thip.qualita.controllo.YCicloCollaudoFase', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.qualita.controllo.CicloCollaudoFaseTM', 'it.mame.thip.qualita.controllo.YCicloCollaudoFaseTM', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('CicloCollaudoFase', 'YCicloCollaudoFase', '1', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.qualita.controllo.CicloCollaudoCaratteristica', 'it.mame.thip.qualita.controllo.YCicloCollaudoCaratt', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.qualita.controllo.CicloCollaudoCaratteristicaTM', 'it.mame.thip.qualita.controllo.YCicloCollaudoCarattTM', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('CicloCollaudoCaratt', 'YCicloCollaudoCaratt', '1', 'N');
 	INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.qualita.controllo.web.CicloCollaudoCarattFormModifier', 'it.mame.thip.qualita.controllo.web.YCicloCollaudoCarattFormModifier', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.qualita.controllo.MisuraCaracteriche', 'it.mame.thip.qualita.controllo.YMisuraCaracteriche', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.qualita.controllo.MisuraCaractericheTM', 'it.mame.thip.qualita.controllo.YMisuraCaractericheTM', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('MisuraCaratteristica', 'YMisuraCaracteriche', '1', 'N');
	INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.qualita.controllo.DocumentoCollaudoTestata', 'it.monchieri.thip.qualita.controllo.YDocumentoCollaudoTestata', '0', 'N');
	INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.qualita.controllo.DocumentiCollaudoRilevazioneMisure', 'it.monchieri.thip.qualita.controllo.YDocumentiCollaudoRilevazioneMisure', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.qualita.controllo.GestoreOrdAcqAnChimica', 'it.mame.thip.qualita.controllo.YGestoreOrdAcqAnChimica', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.magazzino.generalemag.Lotto', 'it.mame.thip.magazzino.generalemag.YLotto', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.magazzino.generalemag.LottoTM', 'it.mame.thip.magazzino.generalemag.YLottoTM', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('Lotto', 'YLotto', '1', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.qualita.controllo.MisuraFase', 'it.monchieri.thip.qualita.controllo.YMisuraFase', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.qualita.controllo.MisuraFaseTM', 'it.monchieri.thip.qualita.controllo.YMisuraFaseTM', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('MisuraFase', 'YMisuraFase', '1', 'N');
