# Class path : com.thera.thermfw.util.Replacement
# Class name : REPLACEMENT
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.offerteCliente.web.OffertaClienteTestataEstrattoFormActionAdapter', 'it.monchieri.thip.vendite.offerteCliente.web.YOffertaClienteTestataEstrattoFormActionAdapter', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.offerteCliente.web.OffertaClienteEstrattoFormModifier', 'it.monchieri.thip.vendite.offerteCliente.web.YOffertaClienteEstrattoFormModifier', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.offerteCliente.web.OffertaClienteRigaPrmFormActionAdapter', 'it.monchieri.thip.vendite.offerteCliente.web.YOffertaClienteRigaPrmFormActionAdapter', '0', 'N');
