-- MAME.VW_DDT_FOR source

CREATE OR REPLACE VIEW MAME.VW_DDT_FOR AS
SELECT
    '000' || substr(DOC_ACQ_TES.ID_NUMERO_DOC,
    6,
    5) AS NUM_DDT_INT ,
    DOC_ACQ_TES.ID_ANNO_DOC AS ANNO_DOC ,
    BBFORPT.FORCFEST AS COD_CF ,
    DOC_ACQ_TES.DATA_DOC AS DATA_DOC ,
    DOC_ACQ_TES.R_CAU_DOC_ACQ AS CODICE_CAUSALE ,
    CASE
        WHEN DOC_ACQ_RIG.R_MAGAZZINO IN ('MP', 'CDE') THEN '1.01'
        ELSE 'N/A'
    END AS COD_DEP ,
    CASE
        WHEN DOC_ACQ_RIG.R_MAG_LAV_ESN IS NOT NULL THEN DOC_ACQ_RIG.R_MAG_LAV_ESN
        WHEN DOC_ACQ_TES.R_MAGAZZINO_TRA IS NOT NULL THEN DOC_ACQ_TES.R_MAGAZZINO_TRA
        ELSE DOC_ACQ_TES.R_MAG_PRELIEVO
    END AS COD_DEP_2 ,
    ARTICOLI.R_CLASSE_FISCALE AS COD_ART ,
    DOC_ACQ_LOT.ID_ARTICOLO AS DES_RIGA ,
    DOC_ACQ_RIG.ID_RIGA_DOC AS NUM_RIGA ,
    DOC_ACQ_RIG.R_UM_ACQ AS UM_ACQ ,
    DOC_ACQ_RIG.QTA_RCV_UM_PRM / 1000 AS QTA_CONSEGNATA ,
    DOC_ACQ_RIG.PREZZO ,
    DOC_ACQ_LOT.ID_LOTTO AS LOTTO ,
    LEFT(DOC_ACQ_TES.NUM_RIF_FOR,
    15) AS NUM_DDT_FORNITORE ,
    DOC_ACQ_TES.DATA_RIF_FOR AS DATA_DOC_FORNITORE ,
    CONFIGURAZIONI.DESCRIZIONE AS LINGOTTO ,
    DOC_ACQ_RIG.R_ANNO_ORD AS RIFERIMENTO_ANNO_ORD_FOR ,
    '000' || substr(DOC_ACQ_RIG.R_NUMERO_ORD,
    5,
    5) AS RIFERIMENTO_NUM_ORD_FOR ,
    DOC_ACQ_RIG.R_RIGA_ORD AS RIFERIMENTO_RIGA_ORD_FOR ,
    MAX(DOC_ACQ_TES.TIMESTAMP_AGG, DOC_ACQ_RIG.TIMESTAMP_AGG, DOC_ACQ_LOT.TIMESTAMP_AGG, CONFIGURAZIONI.TIMESTAMP_AGG) AS TIMESTAMP_AGG
FROM
    THIP.DOC_ACQ_TES DOC_ACQ_TES
INNER JOIN THIP.DOC_ACQ_RIG DOC_ACQ_RIG ON
    DOC_ACQ_TES.ID_AZIENDA = DOC_ACQ_RIG.ID_AZIENDA
    AND DOC_ACQ_TES.ID_ANNO_DOC = DOC_ACQ_RIG.ID_ANNO_DOC
    AND DOC_ACQ_TES.ID_NUMERO_DOC = DOC_ACQ_RIG.ID_NUMERO_DOC
INNER JOIN THIP.FORNITORI_ACQ FORNITORI_ACQ ON
    DOC_ACQ_TES.ID_AZIENDA = FORNITORI_ACQ.ID_AZIENDA
    AND DOC_ACQ_TES.R_FORNITORE = FORNITORI_ACQ.ID_FORNITORE
INNER JOIN FINANCE.BBFORPT BBFORPT ON
    BBFORPT.T01CD = FORNITORI_ACQ.ID_AZIENDA
    AND BBFORPT.FORCD = FORNITORI_ACQ.ID_FORNITORE
INNER JOIN THIP.DOC_ACQ_LOT DOC_ACQ_LOT ON
    DOC_ACQ_RIG.ID_AZIENDA = DOC_ACQ_LOT.ID_AZIENDA
    AND DOC_ACQ_RIG.ID_ANNO_DOC = DOC_ACQ_LOT.ID_ANNO_DOC
    AND DOC_ACQ_RIG.ID_NUMERO_DOC = DOC_ACQ_LOT.ID_NUMERO_DOC
    AND DOC_ACQ_RIG.ID_RIGA_DOC = DOC_ACQ_LOT.ID_RIGA_DOC
INNER JOIN THIP.ARTICOLI ARTICOLI ON
    ARTICOLI.ID_AZIENDA = DOC_ACQ_LOT.ID_AZIENDA
    AND ARTICOLI.ID_ARTICOLO = DOC_ACQ_LOT.ID_ARTICOLO
INNER JOIN THIP.CONFIGURAZIONI CONFIGURAZIONI ON
    CONFIGURAZIONI.ID_AZIENDA = DOC_ACQ_RIG.ID_AZIENDA
    AND CONFIGURAZIONI.ID_CONFIG = DOC_ACQ_RIG.R_CONFIGURAZIONE
WHERE
    DOC_ACQ_TES.ID_ANNO_DOC >= YEAR(CURRENT TIMESTAMP) - 1
    AND DOC_ACQ_TES.R_CAU_DOC_ACQ IN ('MP', 'MPE')
    AND DOC_ACQ_RIG.ID_DET_RIGA_DOC = 0
    AND DOC_ACQ_LOT.ID_DET_RIGA_DOC = 0;