-- MAME.VW_ORD_FOR source

CREATE
    OR REPLACE VIEW MAME.VW_ORD_FOR AS
SELECT
    '000' || substr(
            ORD_ACQ_TES.ID_NUMERO_ORD,
            5,
            5
        ) AS NUM_DOC,
    ORD_ACQ_TES.ID_ANNO_ORDINE AS ANNO_DOC,
    BBFORPT.FORCFEST AS COD_CF,
    ORD_ACQ_TES.DATA_ORDINE AS DATA_DOC,
    ARTICOLI.R_CLASSE_FISCALE AS COD_ART,
    ORD_ACQ_LOT.R_ARTICOLO AS DES_RIGA,
    ORD_ACQ_RIG.ID_RIGA_ORD AS NUM_RIGA,
    ORD_ACQ_RIG.R_UM_ACQ AS UM_BASE,
    ORD_ACQ_LOT.QTA_ORD_UM_ACQ AS QUANT_UM_BASE,
    ORD_ACQ_RIG.PREZZO,
    ORD_ACQ_RIG.NOTA AS NOTE_INT,
    ORD_ACQ_RIG.DATA_CONSEG_CFM AS DATA_CONS_RIGA,
    ID_YNORMA_QLT AS id,
    MAX( ORD_ACQ_TES.TIMESTAMP_AGG, ORD_ACQ_RIG.TIMESTAMP_AGG, ORD_ACQ_LOT.TIMESTAMP_AGG ) AS TIMESTAMP_AGG
FROM
    THIP.ORD_ACQ_TES ORD_ACQ_TES
INNER JOIN(
    SELECT
        ORD_ACQ_TES.ID_AZIENDA,
        ORD_ACQ_TES.ID_ANNO_ORDINE,
        LEFT(
                    ORD_ACQ_TES.ID_NUMERO_ORD,
                    9
                ) AS LEFT_ID_NUMERO_ORD,
        MAX(ORD_ACQ_TES.ID_NUMERO_ORD) AS ID_NUMERO_ORD
    FROM
        THIP.ORD_ACQ_TES ORD_ACQ_TES
    WHERE
        ORD_ACQ_TES.STATO = 'V'
        AND ORD_ACQ_TES.R_CAU_ORD_ACQ = 'MP'
        AND ORD_ACQ_TES.ID_ANNO_ORDINE >= YEAR(
                    CURRENT DATE
                )- 1
    GROUP BY
        ORD_ACQ_TES.ID_AZIENDA,
        ORD_ACQ_TES.ID_ANNO_ORDINE,
        LEFT(
                    ORD_ACQ_TES.ID_NUMERO_ORD,
                    9
                )
        ) ORD_ACQ_TES_VALIDI ON
    ORD_ACQ_TES.ID_AZIENDA = ORD_ACQ_TES_VALIDI.ID_AZIENDA
    AND ORD_ACQ_TES.ID_ANNO_ORDINE = ORD_ACQ_TES_VALIDI.ID_ANNO_ORDINE
    AND ORD_ACQ_TES.ID_NUMERO_ORD = ORD_ACQ_TES_VALIDI.ID_NUMERO_ORD
INNER JOIN FINANCE.BBFORPT BBFORPT ON
    BBFORPT.T01CD = ORD_ACQ_TES.ID_AZIENDA
    AND BBFORPT.FORCD = ORD_ACQ_TES.R_FORNITORE
INNER JOIN THIP.ORD_ACQ_RIG ORD_ACQ_RIG ON
    ORD_ACQ_RIG.ID_AZIENDA = ORD_ACQ_TES.ID_AZIENDA
    AND ORD_ACQ_RIG.ID_ANNO_ORD = ORD_ACQ_TES.ID_ANNO_ORDINE
    AND ORD_ACQ_RIG.ID_NUMERO_ORD = ORD_ACQ_TES.ID_NUMERO_ORD
INNER JOIN MAME.ord_acq_rig_mame ord_acq_rig_mame ON
    ord_acq_rig_mame.ID_AZIENDA = ORD_ACQ_RIG.ID_AZIENDA
    AND ord_acq_rig_mame.ID_ANNO_ORD = ORD_ACQ_RIG.ID_ANNO_ORD
    AND ord_acq_rig_mame.ID_NUMERO_ORD = ORD_ACQ_RIG.ID_NUMERO_ORD
    AND ord_acq_rig_mame.ID_RIGA_ORD = ORD_ACQ_RIG.ID_RIGA_ORD
    AND ord_acq_rig_mame.ID_DET_RIGA_ORD = ORD_ACQ_RIG.ID_DET_RIGA_ORD
INNER JOIN THIP.ORD_ACQ_LOT ORD_ACQ_LOT ON
    ORD_ACQ_RIG.ID_AZIENDA = ORD_ACQ_LOT.ID_AZIENDA
    AND ORD_ACQ_RIG.ID_ANNO_ORD = ORD_ACQ_LOT.ID_ANNO_ORD
    AND ORD_ACQ_RIG.ID_NUMERO_ORD = ORD_ACQ_LOT.ID_NUMERO_ORD
    AND ORD_ACQ_RIG.ID_RIGA_ORD = ORD_ACQ_LOT.ID_RIGA_ORD
INNER JOIN THIP.ARTICOLI ARTICOLI ON
    ARTICOLI.ID_AZIENDA = ORD_ACQ_LOT.ID_AZIENDA
    AND ARTICOLI.ID_ARTICOLO = ORD_ACQ_LOT.R_ARTICOLO
WHERE
    ORD_ACQ_TES.STATO = 'V'
    AND ORD_ACQ_TES.R_CAU_ORD_ACQ = 'MP'
    AND ORD_ACQ_TES.ID_ANNO_ORDINE >= YEAR(
            CURRENT DATE
        )- 1;