-- MAME.WV_QC_ANALISI_ACCIAIERIA source

CREATE OR REPLACE VIEW MAME.WV_QC_ANALISI_ACCIAIERIA AS
SELECT
    LOTTI.ID_LOTTO AS ENTRATA,
    LOTTI.DTA_DOC_ACQ AS DATA,
    LOTTI.LOTTO_ACQUISTO AS COLATA,
    ANAGRAFICO_BAS.ANARASOC AS ACCIAIERIA,
    RIGHT( '000000' || RTRIM( CAST( SGQ_CICLI_TES.ID_PROGRESSIVO + 6000 AS VARCHAR(8))), 6 ) AS ID,
    YNORME_QLT.DSC_ACCIAIO AS ACCIAIO,
    COALESCE( YNORME_QLT.ALIAS_ACCIAIO, '' ) AS ALLIAS_ACCIAIO,
    '' AS SPECIFICA_1,
    '' AS ELAB_ACCIAIO,
    '' AS TIPO_TRAT,
    '' AS NOTE,
    SGQ_DOC_TES.TIMESTAMP_AGG,
    S_AL.VALORE_RILEVATO AS AL,
    S_ALSOL.VALORE_RILEVATO AS ALSOL,
    S_AS.VALORE_RILEVATO AS AS_,
    S_B.VALORE_RILEVATO AS B,
    S_BI.VALORE_RILEVATO AS BI,
    S_C.VALORE_RILEVATO AS C,
    S_CA.VALORE_RILEVATO AS CA,
    S_CB.VALORE_RILEVATO AS CB,
    S_CE.VALORE_RILEVATO AS CE,
    S_CO.VALORE_RILEVATO AS CO,
    S_CR.VALORE_RILEVATO AS CR,
    S_CR_EQ.VALORE_RILEVATO AS CR_EQ,
    S_CU.VALORE_RILEVATO AS CU,
    S_H.VALORE_RILEVATO AS H,
    CASE
        WHEN S_H.R_UM_CLIENTE = 'P%' THEN 1
        ELSE 0
    END AS H_PPM_O_PERC,
    S_JF.VALORE_RILEVATO AS JF,
    S_MN.VALORE_RILEVATO AS MN,
    S_MO.VALORE_RILEVATO AS MO,
    S_N.VALORE_RILEVATO AS N,
    CASE
        WHEN S_N.R_UM_CLIENTE = 'P%' THEN 1
        ELSE 0
    END AS N_PPM_O_PERC,
    S_NB.VALORE_RILEVATO AS NB,
    S_NI.VALORE_RILEVATO AS NI,
    S_O.VALORE_RILEVATO AS O,
    CASE
        WHEN S_O.R_UM_CLIENTE = 'P%' THEN 1
        ELSE 0
    END AS O_PPM_O_PERC,
    S_P.VALORE_RILEVATO AS P,
    S_PB.VALORE_RILEVATO AS PB,
    S_PCM.VALORE_RILEVATO AS PCM,
    S_PRE.VALORE_RILEVATO AS PRE,
    S_S.VALORE_RILEVATO AS S,
    S_SB.VALORE_RILEVATO AS SB,
    S_SI.VALORE_RILEVATO AS SI,
    S_SN.VALORE_RILEVATO AS SN,
    S_TA.VALORE_RILEVATO AS TA,
    S_TI.VALORE_RILEVATO AS TI,
    S_V.VALORE_RILEVATO AS V,
    S_W.VALORE_RILEVATO AS W,
    S_XF.VALORE_RILEVATO AS XF,
    S_ZR.VALORE_RILEVATO AS ZR,
    S_C_N.VALORE_RILEVATO AS C_N,
    S_FE.VALORE_RILEVATO AS FE,
    S_NB_TA.VALORE_RILEVATO AS NB_TA,
    S_Y.VALORE_RILEVATO AS Y,
    S_FORM_1.DESCR_RID_MAME AS AC_FORMULA_1,
    S_FORM_1.VALORE_RILEVATO AS AC_FORMULA_1_VALORE,
    S_FORM_2.DESCR_RID_MAME AS AC_FORMULA_2,
    S_FORM_2.VALORE_RILEVATO AS AC_FORMULA_2_VALORE,
    S_FORM_3.DESCR_RID_MAME AS AC_FORMULA_3,
    S_FORM_3.VALORE_RILEVATO AS AC_FORMULA_3_VALORE,
    S_FORM_4.DESCR_RID_MAME AS AC_FORMULA_4,
    S_FORM_4.VALORE_RILEVATO AS AC_FORMULA_4_VALORE,
    S_FORM_5.DESCR_RID_MAME AS AC_FORMULA_5,
    S_FORM_5.VALORE_RILEVATO AS AC_FORMULA_5_VALORE
FROM
    THIP.SGQ_DOC_TES AS SGQ_DOC_TES
INNER JOIN(
    SELECT
        ID_AZIENDA,
        ID_TIPO_DOCPRV,
        ID_ANNO_DOC,
        ID_NUMERO_DOC,
        ID_RIGA_DOC,
        MAX(ID_NUM_ISTANZA) AS ID_NUM_ISTANZA
    FROM
        THIP.SGQ_DOC_RIG
    GROUP BY
        ID_AZIENDA,
        ID_TIPO_DOCPRV,
        ID_ANNO_DOC,
        ID_NUMERO_DOC,
        ID_RIGA_DOC ) AS SGQ_DOC_RIG_MAX ON
    SGQ_DOC_TES.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND SGQ_DOC_TES.ID_TIPO_DOCPRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND SGQ_DOC_TES.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND SGQ_DOC_TES.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND SGQ_DOC_TES.ID_RIGA = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
INNER JOIN MAME.ORD_ACQ_RIG_MAME AS ORD_ACQ_RIG_MAME ON
    ORD_ACQ_RIG_MAME.ID_AZIENDA = SGQ_DOC_TES.ID_AZIENDA
    AND ORD_ACQ_RIG_MAME.ID_ANNO_ORD = SGQ_DOC_TES.ANNO_ORD_ACQ
    AND ORD_ACQ_RIG_MAME.ID_NUMERO_ORD = SGQ_DOC_TES.NUMERO_ORD_ACQ
    AND ORD_ACQ_RIG_MAME.ID_RIGA_ORD = SGQ_DOC_TES.RIGA_ORD_ACQ
    AND ORD_ACQ_RIG_MAME.ID_DET_RIGA_ORD = SGQ_DOC_TES.DET_RIGA_ORD_ACQ
INNER JOIN MAME.YNORME_QLT AS YNORME_QLT ON
    YNORME_QLT.ID_AZIENDA = ORD_ACQ_RIG_MAME.ID_AZIENDA
    AND YNORME_QLT.ID_NORMA = ORD_ACQ_RIG_MAME.ID_YNORMA_QLT
INNER JOIN THIP.SGQ_CICLI_TES AS SGQ_CICLI_TES ON
    ORD_ACQ_RIG_MAME.ID_AZIENDA = SGQ_CICLI_TES.ID_AZIENDA
    AND ORD_ACQ_RIG_MAME.ID_ANNO_ORD = SGQ_CICLI_TES.ANNO_ORD
    AND ORD_ACQ_RIG_MAME.ID_NUMERO_ORD = SGQ_CICLI_TES.NUMERO_ORD
    AND ORD_ACQ_RIG_MAME.ID_RIGA_ORD = SGQ_CICLI_TES.RIGA_ORD
    AND ORD_ACQ_RIG_MAME.ID_DET_RIGA_ORD = SGQ_CICLI_TES.DET_RIGA_ORD
INNER JOIN THIP.LOTTI AS LOTTI ON
    LOTTI.ID_AZIENDA = SGQ_DOC_TES.ID_AZIENDA
    AND LOTTI.ID_ARTICOLO = SGQ_DOC_TES.R_ARTICOLO
    AND LOTTI.ID_LOTTO = SGQ_DOC_TES.R_LOTTO
    AND LOTTI.R_FORNITORE = SGQ_DOC_TES.R_FORNITORE
INNER JOIN MAME.LOTTI_X AS LOTTI_X ON
    LOTTI.ID_AZIENDA = LOTTI_X.ID_AZIENDA
    AND LOTTI.ID_ARTICOLO = LOTTI_X.ID_ARTICOLO
    AND LOTTI.ID_LOTTO = LOTTI_X.ID_LOTTO
INNER JOIN THIP.FORNITORI_ACQ AS FORNITORI_ACQ ON
    LOTTI.ID_AZIENDA = FORNITORI_ACQ.ID_AZIENDA
    AND LOTTI.R_FORNITORE = FORNITORI_ACQ.ID_FORNITORE
INNER JOIN THIP.ANAGRAFICO_BAS AS ANAGRAFICO_BAS ON
    FORNITORI_ACQ.R_ANAGRAFICO = ANAGRAFICO_BAS.ANACD
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_AL ON
    S_AL.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_AL.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_AL.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_AL.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_AL.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_AL.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_AL.DESCR_RID_MAME = 'Al'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_ALSOL ON
    S_ALSOL.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_ALSOL.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_ALSOL.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_ALSOL.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_ALSOL.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_ALSOL.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_ALSOL.DESCR_RID_MAME = 'Al Sol'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_AS ON
    S_AS.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_AS.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_AS.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_AS.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_AS.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_AS.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_AS.DESCR_RID_MAME = 'As'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_B ON
    S_B.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_B.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_B.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_B.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_B.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_B.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_B.DESCR_RID_MAME = 'B'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_BI ON
    S_BI.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_BI.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_BI.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_BI.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_BI.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_BI.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_BI.DESCR_RID_MAME = 'Bi'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_C ON
    S_C.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_C.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_C.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_C.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_C.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_C.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_C.DESCR_RID_MAME = 'C'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_CA ON
    S_CA.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_CA.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_CA.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_CA.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_CA.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_CA.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_CA.DESCR_RID_MAME = 'Ca'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_CB ON
    S_CB.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_CB.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_CB.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_CB.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_CB.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_CB.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_CB.DESCR_RID_MAME = 'Cb'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_CE ON
    S_CE.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_CE.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_CE.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_CE.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_CE.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_CE.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_CE.DESCR_RID_MAME = 'Ceq'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_CO ON
    S_CO.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_CO.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_CO.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_CO.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_CO.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_CO.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_CO.DESCR_RID_MAME = 'Co'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_CR ON
    S_CR.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_CR.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_CR.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_CR.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_CR.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_CR.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_CR.DESCR_RID_MAME = 'Cr'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_CR_EQ ON
    S_CR_EQ.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_CR_EQ.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_CR_EQ.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_CR_EQ.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_CR_EQ.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_CR_EQ.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_CR_EQ.DESCR_RID_MAME = 'Creq'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_CU ON
    S_CU.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_CU.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_CU.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_CU.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_CU.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_CU.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_CU.DESCR_RID_MAME = 'Cu'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_H ON
    S_H.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_H.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_H.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_H.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_H.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_H.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_H.DESCR_RID_MAME = 'H'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_JF ON
    S_JF.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_JF.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_JF.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_JF.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_JF.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_JF.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_JF.DESCR_RID_MAME = 'J Fact'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_MN ON
    S_MN.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_MN.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_MN.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_MN.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_MN.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_MN.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_MN.DESCR_RID_MAME = 'Mn'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_MO ON
    S_MO.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_MO.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_MO.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_MO.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_MO.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_MO.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_MO.DESCR_RID_MAME = 'Mo'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_N ON
    S_N.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_N.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_N.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_N.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_N.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_N.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_N.DESCR_RID_MAME = 'N'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_NB ON
    S_NB.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_NB.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_NB.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_NB.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_NB.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_NB.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_NB.DESCR_RID_MAME = 'Nb'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_NI ON
    S_NI.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_NI.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_NI.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_NI.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_NI.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_NI.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_NI.DESCR_RID_MAME = 'Ni'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_O ON
    S_O.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_O.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_O.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_O.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_O.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_O.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_O.DESCR_RID_MAME = 'O'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_P ON
    S_P.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_P.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_P.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_P.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_P.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_P.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_P.DESCR_RID_MAME = 'P'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_PB ON
    S_PB.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_PB.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_PB.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_PB.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_PB.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_PB.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_PB.DESCR_RID_MAME = 'Pb'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_PCM ON
    S_PCM.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_PCM.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_PCM.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_PCM.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_PCM.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_PCM.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_PCM.DESCR_RID_MAME = 'PCM'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_PRE ON
    S_PRE.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_PRE.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_PRE.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_PRE.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_PRE.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_PRE.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_PRE.DESCR_RID_MAME = 'Pre'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_S ON
    S_S.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_S.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_S.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_S.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_S.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_S.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_S.DESCR_RID_MAME = 'S'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_SB ON
    S_SB.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_SB.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_SB.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_SB.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_SB.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_SB.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_SB.DESCR_RID_MAME = 'Sb'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_SI ON
    S_SI.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_SI.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_SI.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_SI.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_SI.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_SI.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_SI.DESCR_RID_MAME = 'Si'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_SN ON
    S_SN.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_SN.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_SN.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_SN.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_SN.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_SN.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_SN.DESCR_RID_MAME = 'Sn'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_TA ON
    S_TA.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_TA.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_TA.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_TA.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_TA.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_TA.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_TA.DESCR_RID_MAME = 'Ta'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_TI ON
    S_TI.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_TI.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_TI.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_TI.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_TI.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_TI.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_TI.DESCR_RID_MAME = 'Ti'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_V ON
    S_V.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_V.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_V.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_V.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_V.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_V.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_V.DESCR_RID_MAME = 'V'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_W ON
    S_W.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_W.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_W.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_W.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_W.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_W.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_W.DESCR_RID_MAME = 'W'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_XF ON
    S_XF.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_XF.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_XF.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_XF.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_XF.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_XF.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_XF.DESCR_RID_MAME = 'X Fact'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_ZR ON
    S_ZR.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_ZR.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_ZR.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_ZR.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_ZR.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_ZR.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_ZR.DESCR_RID_MAME = 'Zr'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_C_N ON
    S_C_N.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_C_N.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_C_N.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_C_N.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_C_N.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_C_N.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_C_N.DESCR_RID_MAME = 'C + N'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_FE ON
    S_FE.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_FE.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_FE.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_FE.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_FE.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_FE.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_FE.DESCR_RID_MAME = 'Fe'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_NB_TA ON
    S_NB_TA.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_NB_TA.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_NB_TA.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_NB_TA.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_NB_TA.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_NB_TA.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_NB_TA.DESCR_RID_MAME = 'Nb + Ta'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP AS S_Y ON
    S_Y.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_Y.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_Y.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_Y.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_Y.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_Y.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_Y.DESCR_RID_MAME = 'Y'
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP_FORM AS S_FORM_1 ON
    S_FORM_1.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_FORM_1.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_FORM_1.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_FORM_1.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_FORM_1.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_FORM_1.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_FORM_1.ENUM = 1
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP_FORM AS S_FORM_2 ON
    S_FORM_2.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_FORM_2.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_FORM_2.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_FORM_2.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_FORM_2.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_FORM_2.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_FORM_2.ENUM = 2
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP_FORM AS S_FORM_3 ON
    S_FORM_3.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_FORM_3.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_FORM_3.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_FORM_3.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_FORM_3.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_FORM_3.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_FORM_3.ENUM = 3
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP_FORM AS S_FORM_4 ON
    S_FORM_4.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_FORM_4.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_FORM_4.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_FORM_4.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_FORM_4.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_FORM_4.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_FORM_4.ENUM = 4
LEFT OUTER JOIN MAME.WV_QC_ANALISI_ACCIAIERIA_TMP_FORM AS S_FORM_5 ON
    S_FORM_5.ID_AZIENDA = SGQ_DOC_RIG_MAX.ID_AZIENDA
    AND S_FORM_5.ID_TIPO_DOC_PRV = SGQ_DOC_RIG_MAX.ID_TIPO_DOCPRV
    AND S_FORM_5.ID_ANNO_DOC = SGQ_DOC_RIG_MAX.ID_ANNO_DOC
    AND S_FORM_5.ID_NUMERO_DOC = SGQ_DOC_RIG_MAX.ID_NUMERO_DOC
    AND S_FORM_5.ID_RIGA_DOC = SGQ_DOC_RIG_MAX.ID_RIGA_DOC
    AND S_FORM_5.ID_NUM_ISTANZA = SGQ_DOC_RIG_MAX.ID_NUM_ISTANZA
    AND S_FORM_5.ENUM = 5
    --WHERE SGQ_DOC_TES.TIMESTAMP_AGG >= CURRENT TIMESTAMP - 60 DAYS;