-- MAME.WV_QC_ANALISI_ACCIAIERIA_TMP_FORM source

CREATE OR REPLACE VIEW MAME.WV_QC_ANALISI_ACCIAIERIA_TMP_FORM AS
SELECT
    SGQ_MIS_FAS.ID_AZIENDA,
    SGQ_MIS_FAS.ID_TIPO_DOC_PRV,
    SGQ_MIS_FAS.ID_ANNO_DOC,
    SGQ_MIS_FAS.ID_NUMERO_DOC,
    SGQ_MIS_FAS.ID_RIGA_DOC,
    SGQ_MIS_FAS.ID_NUM_ISTANZA,
    SGQ_MIS_FAS.ID_SEQUENZA_FASE,
    SGQ_MIS_CAR_MAME.DESCR_RID_MAME,
    SGQ_MIS_CAR_MAME.R_UM_CLIENTE,
    SGQ_MISURE.VALORE_RILEVATO,
    SGQ_MISURE.INDICAZIONE_ESITO,
    SGQ_MISURE.STATO,
    SGQ_MIS_CAR_MAME.YFORMULA,
    ROW_NUMBER() OVER(
        PARTITION BY SGQ_MIS_CAR.ID_AZIENDA,
        SGQ_MIS_CAR.ID_TIPO_DOC_PRV,
        SGQ_MIS_CAR.ID_ANNO_DOC,
        SGQ_MIS_CAR.ID_NUMERO_DOC,
        SGQ_MIS_CAR.ID_RIGA_DOC,
        SGQ_MIS_CAR.ID_NUMERO_ISTANZA,
        SGQ_MIS_CAR.ID_SEQUENZA_FASE
ORDER BY
        SGQ_MIS_CAR.ID_AZIENDA,
        SGQ_MIS_CAR.ID_TIPO_DOC_PRV,
        SGQ_MIS_CAR.ID_ANNO_DOC,
        SGQ_MIS_CAR.ID_NUMERO_DOC,
        SGQ_MIS_CAR.ID_RIGA_DOC,
        SGQ_MIS_CAR.ID_NUMERO_ISTANZA,
        SGQ_MIS_CAR.ID_SEQUENZA_FASE
    ) AS ENUM,
    SGQ_MIS_CAR.TIMESTAMP_AGG AS TIMESTAMP_AGG
FROM
    THIP.SGQ_DOC_TES AS SGQ_DOC_TES
INNER JOIN THIP.SGQ_MIS_FAS AS SGQ_MIS_FAS ON
    SGQ_MIS_FAS.ID_AZIENDA = SGQ_DOC_TES.ID_AZIENDA
    AND SGQ_MIS_FAS.ID_TIPO_DOC_PRV = SGQ_DOC_TES.ID_TIPO_DOCPRV
    AND SGQ_MIS_FAS.ID_ANNO_DOC = SGQ_DOC_TES.ID_ANNO_DOC
    AND SGQ_MIS_FAS.ID_NUMERO_DOC = SGQ_DOC_TES.ID_NUMERO_DOC
    AND SGQ_MIS_FAS.ID_RIGA_DOC = SGQ_DOC_TES.ID_RIGA
INNER JOIN THIP.SGQ_MIS_CAR AS SGQ_MIS_CAR ON
    SGQ_MIS_CAR.ID_AZIENDA = SGQ_MIS_FAS.ID_AZIENDA
    AND SGQ_MIS_CAR.ID_TIPO_DOC_PRV = SGQ_MIS_FAS.ID_TIPO_DOC_PRV
    AND SGQ_MIS_CAR.ID_ANNO_DOC = SGQ_MIS_FAS.ID_ANNO_DOC
    AND SGQ_MIS_CAR.ID_NUMERO_DOC = SGQ_MIS_FAS.ID_NUMERO_DOC
    AND SGQ_MIS_CAR.ID_RIGA_DOC = SGQ_MIS_FAS.ID_RIGA_DOC
    AND SGQ_MIS_CAR.ID_NUMERO_ISTANZA = SGQ_MIS_FAS.ID_NUM_ISTANZA
    AND SGQ_MIS_CAR.ID_SEQUENZA_FASE = SGQ_MIS_FAS.ID_SEQUENZA_FASE
INNER JOIN MAME.SGQ_MIS_CAR_MAME AS SGQ_MIS_CAR_MAME ON
    SGQ_MIS_CAR_MAME.ID_AZIENDA = SGQ_MIS_CAR.ID_AZIENDA
    AND SGQ_MIS_CAR_MAME.ID_TIPO_DOC_PRV = SGQ_MIS_CAR.ID_TIPO_DOC_PRV
    AND SGQ_MIS_CAR_MAME.ID_ANNO_DOC = SGQ_MIS_CAR.ID_ANNO_DOC
    AND SGQ_MIS_CAR_MAME.ID_NUMERO_DOC = SGQ_MIS_CAR.ID_NUMERO_DOC
    AND SGQ_MIS_CAR_MAME.ID_RIGA_DOC = SGQ_MIS_CAR.ID_RIGA_DOC
    AND SGQ_MIS_CAR_MAME.ID_NUMERO_ISTANZA = SGQ_MIS_CAR.ID_NUMERO_ISTANZA
    AND SGQ_MIS_CAR_MAME.ID_SEQUENZA_FASE = SGQ_MIS_CAR.ID_SEQUENZA_FASE
    AND SGQ_MIS_CAR_MAME.ID_SEQUENZA_CAR = SGQ_MIS_CAR.ID_SEQUENZA_CAR
INNER JOIN THIP.SGQ_MISURE AS SGQ_MISURE ON
    SGQ_MISURE.ID_AZIENDA = SGQ_MIS_CAR_MAME.ID_AZIENDA
    AND SGQ_MISURE.ID_TIPO_DOC_PRV = SGQ_MIS_CAR_MAME.ID_TIPO_DOC_PRV
    AND SGQ_MISURE.ID_ANNO_DOC = SGQ_MIS_CAR_MAME.ID_ANNO_DOC
    AND SGQ_MISURE.ID_NUMERO_DOC = SGQ_MIS_CAR_MAME.ID_NUMERO_DOC
    AND SGQ_MISURE.ID_RIGA_DOC = SGQ_MIS_CAR_MAME.ID_RIGA_DOC
    AND SGQ_MISURE.ID_NUMERO_ISTANZA = SGQ_MIS_CAR_MAME.ID_NUMERO_ISTANZA
    AND SGQ_MISURE.ID_SEQUENZA_FASE = SGQ_MIS_CAR_MAME.ID_SEQUENZA_FASE
    AND SGQ_MISURE.ID_SEQUENZA_CAR = SGQ_MIS_CAR_MAME.ID_SEQUENZA_CAR
WHERE
    MAX(SGQ_MIS_FAS.TIMESTAMP_AGG, SGQ_DOC_TES.TIMESTAMP_AGG) >= CURRENT TIMESTAMP - 60 DAYS
    AND SGQ_MIS_CAR_MAME.DESCR_RID_MAME NOT IN(
        'Al', 'Al Sol', 'As', 'B', 'Bi', 'C', 'Ca', 'Cb', 'Ceq', 'Co', 'Cr', 'Creq', 'Cu', 'H', 'J Fact', 'Mn', 'Mo', 'N', 'Nb', 'Ni', 'O', 'P', 'Pb', 'PCM', 'Pre', 'S', 'Sb', 'Si', 'Sn', 'Ta', 'Ti', 'V', 'W', 'X Fact', 'Zr', 'C + N', 'Fe', 'Nb + Ta', 'Y'
    )
    AND SGQ_MIS_CAR_MAME.YFORMULA IS NOT NULL;