    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.qualita.controllo.MisuraFase', 'it.monchieri.thip.qualita.controllo.YMisuraFase', '0', 'Y');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.qualita.controllo.MisuraFaseTM', 'it.monchieri.thip.qualita.controllo.YMisuraFaseTM', '0', 'Y');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('MisuraFase', 'YMisuraFase', '1', 'Y');
